@ECHO off

SET JAVA_HOME="C:\Program Files (x86)\Java\jdk1.8.0_161"
SET ANDROID_SDK_HOME=%userprofile%\AppData\Local\Android\Sdk
SET ANDROID_NDK_HOME=%ANDROID_SDK_HOME%\ndk-bundle
SET CMAKE=%ANDROID_SDK_HOME%\cmake\3.10.2.4988404\bin
SET ANDROID_API_LEVEL=26
SET QT_PATH=D:\Qt\5.14.0\android
SET MAKE_PROGRAM=%CMAKE%/ninja
rem SET ANDROID_ABI=arm64-v8a
SET ANDROID_ABI=armeabi-v7a
rem SET ANDROID_ABI=x86
rem SET ANDROID_ABI=x86_64

IF EXIST build_android GOTO MARK1

MKDIR build_android
CD build_android
%CMAKE%\cmake.exe ^
	-GNinja^
	-DCMAKE_BUILD_TYPE=Release^
	-DCMAKE_TOOLCHAIN_FILE=%ANDROID_NDK_HOME%/build/cmake/android.toolchain.cmake^
	-DCMAKE_SYSTEM_NAME=Android^
	-DCMAKE_SYSTEM_VERSION=%ANDROID_API_LEVEL%^
	-DANDROID_ARCH_ABI=%ANDROID_ABI%^
	-DANDROID_NATIVE_API_LEVEL=%ANDROID_API_LEVEL%^
	-DCMAKE_PREFIX_PATH=%QT_PATH%^
	-DCMAKE_FIND_ROOT_PATH=%QT_PATH%^
	-DCMAKE_ANDROID_ARM_NEON=ON^
	-DANDROID_ABI=%ANDROID_ABI%^
	-DCMAKE_MAKE_PROGRAM=%MAKE_PROGRAM%^
	-DANDROID_TOOLCHAIN=clang^
	../%1
CD ..

:MARK1

CD build_android
%MAKE_PROGRAM%
rem %MAKE_PROGRAM% install
CD ..
